2019-01-16 12:31:31,916 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTQ3NjY0MDg3LjA1NTQ2NX0.lIwwqhBvezAHD8F71F-fwIv6Am-8KFFwxBV9RoDJ2VM [GET] [in /Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/MasonBaran/first_flask/app/routes.py", line 178, in reset_password
    user.set_password(form.password.data)
  File "/Users/MasonBaran/first_flask/app/models.py", line 36, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 230, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 192, in _hash_internal
    hashfunc=hash_func)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 64, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 104, in pbkdf2_bin
    keylen)
TypeError: a bytes-like object is required, not 'NoneType'
2019-01-16 12:34:45,904 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 12:36:26,506 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 12:36:39,599 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTQ3NjY0Mzk0LjMyNTkwOX0.RSLGGIzsYn7GZrw4nW4Ov-llGbyHS4vyPZdBv0lu1bg [GET] [in /Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/MasonBaran/first_flask/app/routes.py", line 179, in reset_password
    user.set_password(form.password.data)
  File "/Users/MasonBaran/first_flask/app/models.py", line 36, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 230, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 192, in _hash_internal
    hashfunc=hash_func)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 64, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 104, in pbkdf2_bin
    keylen)
TypeError: a bytes-like object is required, not 'NoneType'
2019-01-16 12:41:26,354 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 12:41:32,389 ERROR: Exception on /reset_password_request [POST] [in /Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/MasonBaran/first_flask/app/routes.py", line 164, in reset_password_request
    send_password_request(user)
  File "/Users/MasonBaran/first_flask/app/email.py", line 20, in send_password_request
    user=user, token=token),
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/MasonBaran/first_flask/app/templates/email/reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'reset_password_request' instead?
2019-01-16 12:42:09,380 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 12:42:14,538 ERROR: Exception on /reset_password_request [GET] [in /Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/MasonBaran/first_flask/app/routes.py", line 163, in reset_password_request
    if user:
UnboundLocalError: local variable 'user' referenced before assignment
