2019-01-16 12:17:12,720 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTQ3NjYzMjIwLjU4NDgxODh9._dfxwk2l_AJxt77etTLFeKaeei3YvOmb3f5nX9U97f8 [GET] [in /Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/MasonBaran/first_flask/app/routes.py", line 178, in reset_password
    user.set_password(form.password.data)
  File "/Users/MasonBaran/first_flask/app/models.py", line 36, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 230, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 192, in _hash_internal
    hashfunc=hash_func)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 64, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 104, in pbkdf2_bin
    keylen)
TypeError: a bytes-like object is required, not 'NoneType'
2019-01-16 12:20:39,461 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTQ3NjYzMjIwLjU4NDgxODh9._dfxwk2l_AJxt77etTLFeKaeei3YvOmb3f5nX9U97f8 [GET] [in /Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/MasonBaran/first_flask/app/routes.py", line 178, in reset_password
    user.set_password(form.password.data)
  File "/Users/MasonBaran/first_flask/app/models.py", line 36, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 230, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 192, in _hash_internal
    hashfunc=hash_func)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 64, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 104, in pbkdf2_bin
    keylen)
TypeError: a bytes-like object is required, not 'NoneType'
2019-01-16 12:24:39,465 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 12:24:56,157 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTQ3NjYzNjg4LjE4ODA5NX0.Mq9FEZdrHrzYONIc6MQdA1a6E6BZho2MZdC9_AZ8Mzc [GET] [in /Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/MasonBaran/first_flask/app/routes.py", line 178, in reset_password
    user.set_password(form.password.data)
  File "/Users/MasonBaran/first_flask/app/models.py", line 36, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 230, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 192, in _hash_internal
    hashfunc=hash_func)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 64, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 104, in pbkdf2_bin
    keylen)
TypeError: a bytes-like object is required, not 'NoneType'
2019-01-16 12:27:24,580 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 12:27:41,040 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6NCwiZXhwIjoxNTQ3NjYzODUxLjA5MDU2Njl9.igxOuCF8pYM9XjlF21a9JFZOIFDRMBKDr61TwoHP7c4 [GET] [in /Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/MasonBaran/first_flask/app/routes.py", line 178, in reset_password
    user.set_password(form.password.data)
  File "/Users/MasonBaran/first_flask/app/models.py", line 36, in set_password
    self.password_hash = generate_password_hash(password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 230, in generate_password_hash
    h, actual_method = _hash_internal(method, salt, password)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 192, in _hash_internal
    hashfunc=hash_func)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 64, in pbkdf2_hex
    rv = pbkdf2_bin(data, salt, iterations, keylen, hashfunc)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/werkzeug/security.py", line 104, in pbkdf2_bin
    keylen)
TypeError: a bytes-like object is required, not 'NoneType'
2019-01-16 12:30:28,784 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 12:31:18,091 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
