2019-01-15 18:50:58,613 ERROR: Exception on /index [GET] [in /Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/MasonBaran/first_flask/app/routes.py", line 36, in index
    next_url=next_url, prev_url=prev_url)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/MasonBaran/first_flask/app/templates/index.html", line 27, in template
    {% endblock %}
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 212, in parse_if
    node.body = self.parse_statements(('name:elif', 'name:else',
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2019-01-15 18:51:58,583 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:43]
2019-01-16 08:34:57,724 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:43]
2019-01-16 08:41:23,766 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:43]
2019-01-16 08:43:21,572 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:43]
2019-01-16 08:45:13,342 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:43]
2019-01-16 09:12:20,044 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 09:43:20,101 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 09:53:55,095 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 09:59:39,259 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 11:09:04,781 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 11:09:25,369 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 11:52:07,963 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 11:52:28,462 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 11:52:40,640 ERROR: Exception on /reset_password_request [GET] [in /Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/MasonBaran/first_flask/app/routes.py", line 161, in reset_password_request
    user = User.query.filter_by(form.email.data).first()
TypeError: filter_by() takes 1 positional argument but 2 were given
2019-01-16 11:56:15,066 INFO: Microblog startup [in /Users/MasonBaran/first_flask/app/__init__.py:45]
2019-01-16 11:57:56,814 ERROR: Exception on /reset_password_request [POST] [in /Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/MasonBaran/first_flask/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/MasonBaran/first_flask/app/routes.py", line 163, in reset_password_request
    send_password_request(user)
  File "/Users/MasonBaran/first_flask/app/email.py", line 16, in send_password_request
    sender=app.config['Admins'][0],
KeyError: 'Admins'
